### PR TITLE
Fixed reference to config file in insert script

### PR DESCRIPTION
**Pull request by mheadd**
The script to insert test data fails because the reference to the config file is broken.

### CODE REVIEW

**Comment by chriswhong** [comment]
This is referencing the config directory, not a file.  Was it throwing an error?

**Comment by mheadd** [comment]
Yeah. It was retiring out on me.

**Comment by mheadd** [comment]
Erroring

**Comment by mheadd** [comment]
Maybe just the require in dataset.js?

**Comment by chriswhong** [comment]
I just added some clarification on how to properly run insert.js:
https://github.com/chriswhong/ReallySimpleOpenData/tree/master/scripts

Take a look and let me know if it works for you.  Be sure to pull to get all the latest changes.

**Comment by mheadd** [comment]
That works. Thanks!

**Pull request closed without merging**
